swagger: "2.0"
info:
  version: "1.0.0"
  title: inventory-application
host: localhost:10010
basePath: /v1
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /inventory-entry:
    x-swagger-router-controller: inventory-controller
    post:
      description: Creates a new inventory entry
      operationId: create
      parameters:
        - name: inventory_entry
          in: body
          description: inventory entry object
          required: true
          schema:
            required:
              - item_id
              - status_id
              - location_id
              - end_user_id
            properties:
              item_id:
                type: integer
              status_id:
                type: integer
              location_id:
                type: integer
              end_user_id:
                type: integer
              comments:
                type: string
      responses:
        "201":
          description: Record created
        "400":
          description: Bad request. Usually validation errors.
    get:
      description: Returns a list of inventory entries
      operationId: getAll
      responses:
        "200":
          description: Success.
        "400":
          description: Bad request.
  /inventory-entry/{id}:
    x-swagger-router-controller: inventory-controller
    patch:
      description: Updates an inventory entry
      operationId: updateEntry
      parameters:
        - name: id
          in: path
          type: string
          required: true
        - name: inventory_entry
          in: body
          description: inventory entry object
          required: true
          schema:
            properties:
              item_id:
                type: string
              status_id:
                type: string
              location_id:
                type: string
              end_user_id:
                type: string
              comments:
                type: string     
      responses:
        "200":
          description: Record updated
        "400":
          description: Bad request. Usually validation errors.
  /end-user:
    x-swagger-router-controller: end-user-controller
    get:
      description: Returns a list of all end users 
      operationId: getAll
      responses:
        "200": 
          description: Success
        "400":
          description: Bad request.
    post:
      description: Creates a new enduser
      operationId: createEndUser
      parameters:
        - name: end_user
          in: body
          description: end user object
          required: true
          schema:
            required:
              - first_name
              - last_name
              - department_id
            properties:
              first_name:
                type: string
              last_name:
                type: string
              department_id:
                type: integer

      responses:
        "201":
          description: User created
        "400":
          description: Bad request. Usually validation errors.
  /end-user/{id}:
    x-swagger-router-controller: end-user-controller
    get:
      description: Gets an end-user by Id
      operationId: get
      parameters:
        - name: id
          in: path
          type: string
          required: true
      responses:
        "200": 
          description: Success.
        "400":
          description: Bad request.
  /item:
    x-swagger-router-controller: item-controller
    get:
      description: Returns a list of all inventory items
      operationId: getAll
      responses:
        "200":
          description: Success.
        "400":
          description: Bad request.
    post:
      description: Creates an inventory item
      operationId: create
      parameters:
        - name: item
          in: body
          description: item object
          required: true
          schema:
            required:
              - type_id
              - brand_id
              - model_no
              - serial_no
              - tag
            properties:
              type_id:
                type: integer
              brand_id:
                type: integer
              model_no:
                type: string
              serial_no:
                type: string
              tag:
                type: string
      responses:
        "201":
          description: Item created
        "400":
          description: Bad request. Usually validation errors.
  /item/{id}:
    x-swagger-router-controller: item-controller
    get:
      description: Returns item by Id
      operationId: get
      parameters:
        - name: id
          in: path
          type: string
          required: true
      responses:
        "200":
          description: Success.
        "400":
          description: Bad request.
  /item-type:
    x-swagger-router-controller: item-controller
    get:
      description: Returns a list of all item types
      operationId: getAllItemTypes
      responses:
        "200":
          description: Success.
        "400":
          description: Bad request.
  # This makes it so you can get the swagger file from /api/v1/swagger.
  /swagger:
    x-swagger-pipe: swagger_raw

# # complex objects have schema definitions
# definitions:

